name: CI/CD Frontend - Innovatech Chile (Despachos)

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ep2-frontend-despacho
  ECS_CLUSTER: innovatech-cluster
  ECS_SERVICE: innovatech-frontend-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    name: Build, Push y Deploy Frontend a ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push imagen a ECR
        run: |
          docker build \
            --build-arg VITE_API_DESPACHOS_URL=http://${{ secrets.ALB_BACKEND_HOST }}:8081 \
            --build-arg VITE_API_VENTAS_URL=http://${{ secrets.ALB_BACKEND_HOST }}:8080 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Forzar nuevo despliegue en ECS
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment

      - name: Esperar a que el servicio se estabilice
        run: |
          aws ecs wait services-stable \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }}

      - name: Confirmar estado final
        run: |
          aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }} \
            --query "services[0].{Status:status,Running:runningCount,Desired:desiredCount}" \
            --output table